Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vbox|
    vbox.name = "phx-origin"
  end
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip: "192.168.33.117"
  config.ssh.insert_key = false
  config.vm.provision "shell", path: "initialize.sh"
end
